### ISSUE TITLE
シラバスのデータについて

### ISSUE THREAD

**Issue by HarukiSugimoto** [wasedaconnect/waseda_connect#2]
時間割はユーザそれぞれが違うと思うが，各々DBサーバに登録するのか？それともローカル(携帯)に保存するのか？
そもそもどのようなデータ型で保存するか？

**Comment by katsuki-code** [comment]
コストだけ考えるとローカル？
でも他機能、特に出欠席機能（時間割から確認時間と出席判定になる位置情報を取得して実際の位置情報と比較）をやるためにはサーバーがいい気がする。
